# Generated by Django 5.2.1 on 2025-06-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='timezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
    ]
